[build-system]
requires = [
    "setuptools",
    "wheel",
    "ninja",
    "torch",
]
build-backend = "setuptools.build_meta"

[project]
name = "cublade"
version = "0.1.0"
description = "A growing toolbox of GPU blades"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
